# Generated by Django 3.2.16 on 2023-11-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentsinorders',
            name='refuce',
            field=models.BooleanField(default=False),
        ),
    ]
