# Generated by Django 3.2.16 on 2023-11-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicamentsinorders_refuce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentsinorders',
            name='refuce',
        ),
        migrations.CreateModel(
            name='RefuceOrdersCurier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuces', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuces', to='api.order')),
            ],
        ),
    ]
